# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190328_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
